right_format = """
$kubernetes\
$helm\
"""

format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#86BBD8 bg:#06969A)\
$os\
${custom.multipass}\
${custom.wsl}\
$shell\
[](fg:#06969A bg:#33658A)\
$hostname\
${custom.shortname}\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[shell]
powershell_indicator = '❯'
format = '[$incidcator]($style)'
style = 'bg:#06969A'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
unknown_indicator = '?'
disabled = false

[custom.shortname]
command = 'printf "  %s\t" $(hostname)' # shows output of command
format = '[$output]($style)'
style = 'bg:#06969A'
disabled = false

[custom.wsl]
command = 'printf "%s" "WSL"' # shows output of command
when = ''' test -f /etc/wsl.conf '''
format = '[$output ]($style)'
style = 'bold fg:#6cd9d2 bg:#06969A'
disabled = false

[custom.multipass]
command = 'echo "MULTIPASS"' # shows output of command
when = ''' test -f /run/cloud-init/cloud-id-multipass '''
format = '[$name $output]($style)'
style = "bold bg:#33658a"
disabled = false

[hostname]
ssh_only = false
format = '[ $hostname ]($style)'
#style = "bold italic fg:#509bb3 bg:#33658A"
#style = "bold italic fg:#67b0c7 bg:#33658A"
style = "bold italic fg:#7ec3d9 bg:#33658A"


disabled = false

[localip]
ssh_only = false
format = '[$localipv4]($style)'
style = "bg:#06969A"
disabled = false

[helm]
format = '[$symbol $version](bold white) '
symbol = "󱃾 "
disabled = false
# You can also replace your username with a neat symbol like   or disable this
# and use the os module below

[kubernetes]
symbol = "󱃾"
format = '[$symbol$context]($style)'
style = "fg:#ff5cd0 "
disabled = false

[username]
show_always = true
style_user = "fg:#ff5cd0 bg:#9A348E"
style_root = "bold fg:#2f094a bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '[ $symbol]($style)'
style = 'fg:#7dfaf2 bg:#06969A'
disabled = false # Disabled by default

[directory]
#style = "bold red bg:#DA627D"
style = "bold italic fg:#f5d0d7 bg:#DA628D"
#style = "underline bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲"


[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
style = "bg:#86BBD8"

[package]
symbol = "󰏗 "

