format = """
[](fg:#DA627D)\
$username\
$hostname\
${custom.zsh}\
${custom.bash}\
$os\
$direnv\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#CEE26B)\
${custom.repo_name}\
[](fg:#CEE26B bg:#39af9C)\
$directory\
[](fg:#36a99C)\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = '[](bold green) '
error_symbol = '[ ](bold red) '

[direnv]
disabled = false

[shell]
powershell_indicator = '❯'
format = '[$incidcator]($style)'
style = 'bg:#9A348E fg:#2f094a'
bash_indicator = ''
zsh_indicator = 'zsh'
unknown_indicator = '?'
disabled = false

[custom.shortname]
command = 'printf " %s \t" $(hostname)' # shows output of command
format = '[$output]($style)'
style = 'fg:cyan bg:#06969A'
disabled = true

[custom.wsl]
command = "$(basename $(echo $KUBECONFIG) | cut -d. -f1 | tr '[:lower:]' '[:upper:]')" # shows output of command
style = 'bg:#9A348E fg:#2f094a'
shell = ["zsh"]
when = '''echo $SHELL test -f /etc/wsl.conf '''
format = '[$output ]($style)'
disabled = false

# Indicates when in bash shell.
[custom.bash]
command = ''' echo $'\uebca' bash '''
when = '''test "$STARSHIP_SHELL" = "bash" '''
format = '[ $output ]($style)'
style = "bold fg:#fbdfc0 bg:#DA627D"

# Indicates when in fish shell.
[custom.zsh]
command = ''' echo -n zsh '''
when = '''test "$STARSHIP_SHELL" = "zsh" '''
style = "bold fg:#fbdfc0 bg:#DA627D"
format = '[ $output ]($style)'

[custom.repo_name]
command = "git remote get-url origin | cut -d: -f2" # shows output of command
shell = ["zsh"]
when = '''git rev-parse --is-inside-work-tree'''
format = '([ $symbol](fg:#3DA15C bg:#CEE26B)[$output ]($style))'
style = 'fg:#3DA15C bg:#CEE26B'
disabled = false
symbol = " "

[custom.repo_root]
command = "git rev-parse --show-toplevel | xargs realpath -s --relative-to=/IAC/PAIL/ | xargs printf '/'" # shows output of command
shell = ["zsh"]
when = ''' test -f /etc/wsl.conf '''
format = '[ $output ]($style)'
style = 'fg:#e68983 bg:#DA627D'
disabled = true

[custom.prod]
command = "basename $(echo $KUBECONFIG) | cut -d. -f1 | tr '[:lower:]' '[:upper:]' | grep -q -e '[PB]DC' && echo PROD"
shell = ["zsh"]
when = '''test -n KUBECONFIG'''
format = '[$output]($style)'
style = 'bold fg:#0df2c3 bg:#06969A'
disabled = false

[custom.uat]
command = "basename $(echo $KUBECONFIG) | cut -d. -f1 | tr '[:lower:]' '[:upper:]' | grep -q 'UAT' && echo UAT"
shell = ["zsh"]
when = '''test -n KUBECONFIG'''
format = '[$output]($style)'
style = 'bold fg:#0df2c3 bg:#06969A'
disabled = false

[custom.dev]
command = "basename $(echo $KUBECONFIG) | cut -d. -f1 | tr '[:lower:]' '[:upper:]' | grep -q 'DEV' && echo DEV"
style = 'bold fg:#0df2c3 bg:#06969A'
shell = ["zsh"]
when = '''test -n KUBECONFIG'''
format = '[$output]($style)'
disabled = false

[custom.qa]
command = "basename $(echo $KUBECONFIG) | cut -d. -f1 | tr '[:lower:]' '[:upper:]' | grep -q 'QA' && echo QA"
shell = ["zsh"]
when = '''test -n KUBECONFIG'''
format = '[$output]($style)'
style = 'bold fg:#0df2c3 bg:#06969A'
disabled = false

[custom.k8s_ns]
command = "kubectl config view --minify -o jsonpath='{.namespace}'"
shell = ["zsh"]
style = 'bold fg:#0df2c3 bg:#06969A'
when = '''test -n KUBECONFIG'''
format = '[$symbol $output]($style)'
disabled = false

[custom.mgmt]
command = "basename $(echo $KUBECONFIG) | cut -d. -f1 | tr '[:lower:]' '[:upper:]' | grep -q -e 'PIT' -e 'PHL' -e 'MDT' -e 'ALP' && echo MGMT"
shell = ["zsh"]
when = '''test -n KUBECONFIG'''
format = '[ ]($style)'
style = 'bold italic fg:#0df2c3 bg:#06969A'
disabled = false

[hostname]
ssh_only = false
format = '[ $hostname ]($style)'
#style = "bold italic fg:#509bb3 bg:#33658A"
#style = "bold italic fg:#67b0c7 bg:#33658A"
style = "bold italic fg:#6cd9d2 bg:#06969A"
disabled = true

[localip]
ssh_only = false
format = '[$localipv4]($style)'
disabled = false

[helm]
format = '[$symbol $version](bold white) '
symbol = " 󱃾 "
disabled = true
# You can also replace your username with a neat symbol like   or disable this
# and use the os module below

[kubernetes]
symbol = "󱃾"
#format = '[$symbol $context ]($style)'
format = '[ $context ](bold fg:#a9ffd2 bg:#06969A)[](bold fg:#06969A bg:#33658A)[ $symbol $cluster]($style)[ \(($namespace)\) ](bold bg:#33658A fg:#a9ffd2)'
style = "fg:#0df2c3 bg:#33658A"
disabled = false
contexts = [
  { context_pattern = ".*DEV-.*", style = "fg:#a9ffd2 bg:#33658A", symbol = "󱃾", context_alias = "DEV"},
  { context_pattern = ".*QA-.*", style = "fg:#a9ffd2 bg:#33658A", symbol = "󱃾", context_alias = "QA"},
  { context_pattern = ".*[PB]DC-.*", style = "fg:#a9ffd2 bg:#33658A", symbol = "󱃾", context_alias = "PROD"},
  { context_pattern = ".*UAT-.*", style = "fg:#a9ffd2 bg:#33658A", symbol = "󱃾", context_alias = "UAT"},
]

#[[kubernetes.contexts]]
# "bold red" style + default symbol when Kubernetes current context name equals "production" *and* the current user
# equals "admin_user"
#context_pattern = ".*PDC.*"
#user_pattern = "*dev*"
#style = "bold red"
#context_aliases = "PROD"
#user_alias = "admin"

[username]
show_always = false
style_user = "fg:#e68983 bg:#DA627D"
style_root = "bold fg:#e68983 bg:#DA627D"
format = '[$user]($style)'
disabled = false


# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '[$symbol]($style)'
style = " fg:#fbdfc0 bg:#DA627D"
disabled = false # Disabled by default

[directory]
truncation_length = 3
truncation_symbol = "/"
truncate_to_repo = true
style = 'bg:#36a99C fg:#a9ffd2'
format = '[ $path ]($style)[$read_only]($read_only_style)'

# #b9E26B
# #39d49C
# #399f9C
# #4a9d0B


# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"EKSA" = "PAiL"
"src" = "code"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bold fg:#fbdfc0 bg:#FCA17D"
format = '[ ($symbol $branch(:$remote_branch) )]($style)'

[git_status]
style = "fg:#fbdfc0 bg:#FCA17D"
format = '[ $all_status$ahead_behind ]($style)'
disabled = true

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲"


[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
style = "bg:#86BBD8"

[package]
symbol = "󰏗 "
